import chalk from 'chalk';
import fs from 'fs';
import path from 'path';
import { FileExplanation } from './llm.js';

export type OutputFormat = 'terminal' | 'md' | 'html';

const STATUS_ICON: Record<string, string> = {
  added: '✚',
  deleted: '✖',
  modified: '✎',
  renamed: '➜',
};

// ─── Terminal output ──────────────────────────────────────────────────────────

export function printFileExplanation(exp: FileExplanation): void {
  const icon = STATUS_ICON[exp.status] ?? '•';
  console.log();
  console.log(chalk.bold.cyan(`${icon} ${exp.filename}`));
  console.log(chalk.white(exp.explanation));
  if (exp.risks && exp.risks.toLowerCase() !== 'none') {
    console.log();
    console.log(chalk.yellow('⚠  Risks: ') + chalk.yellow(exp.risks));
  }
}

export function printGlobalSummary(summary: string): void {
  console.log();
  console.log(chalk.bold.green('─'.repeat(60)));
  console.log(chalk.bold.green('Overall summary'));
  console.log(chalk.bold.green('─'.repeat(60)));
  console.log(chalk.green(summary));
  console.log();
}

export function printError(message: string): void {
  console.error(chalk.bold.red('✖ Error: ') + chalk.red(message));
}

export function printInfo(message: string): void {
  console.log(chalk.dim(message));
}

// ─── Markdown output ──────────────────────────────────────────────────────────

function buildMarkdown(
  explanations: FileExplanation[],
  globalSummary: string
): string {
  const lines: string[] = [];
  const now = new Date().toISOString().replace('T', ' ').slice(0, 19);

  lines.push('# Why Changed');
  lines.push('');
  lines.push(
    `> Generated by [why-changed](https://www.npmjs.com/package/why-changed) on ${now}`
  );
  lines.push('');

  for (const exp of explanations) {
    const icon = STATUS_ICON[exp.status] ?? '•';
    lines.push(`## ${icon} \`${exp.filename}\``);
    lines.push('');
    lines.push(exp.explanation);
    lines.push('');
    if (exp.risks && exp.risks.toLowerCase() !== 'none') {
      lines.push(`**⚠ Risks:** ${exp.risks}`);
      lines.push('');
    }
    lines.push(`**Summary:** ${exp.summary}`);
    lines.push('');
    lines.push('---');
    lines.push('');
  }

  lines.push('## Overall Summary');
  lines.push('');
  lines.push(globalSummary);
  lines.push('');

  return lines.join('\n');
}

// ─── HTML output ─────────────────────────────────────────────────────────────

function buildHtml(
  explanations: FileExplanation[],
  globalSummary: string
): string {
  const escape = (s: string) =>
    s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

  const now = new Date().toISOString().replace('T', ' ').slice(0, 19);

  const fileCards = explanations
    .map((exp) => {
      const icon = STATUS_ICON[exp.status] ?? '•';
      const risksHtml =
        exp.risks && exp.risks.toLowerCase() !== 'none'
          ? `<p class="risks"><span class="tag risks-tag">⚠ Risks</span> ${escape(exp.risks)}</p>`
          : '';
      return `
    <div class="card">
      <h2><span class="icon">${icon}</span> <code>${escape(exp.filename)}</code>
        <span class="badge badge-${exp.status}">${exp.status}</span>
      </h2>
      <p class="explanation">${escape(exp.explanation)}</p>
      ${risksHtml}
      <p class="summary"><span class="tag summary-tag">Summary</span> ${escape(exp.summary)}</p>
    </div>`;
    })
    .join('\n');

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Why Changed</title>
  <style>
    *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, monospace;
      background: #0d1117; color: #c9d1d9; padding: 2rem;
      max-width: 900px; margin: 0 auto;
    }
    h1 { color: #58a6ff; font-size: 1.8rem; margin-bottom: 0.25rem; }
    .meta { color: #8b949e; font-size: 0.85rem; margin-bottom: 2rem; }
    .card {
      background: #161b22; border: 1px solid #30363d; border-radius: 8px;
      padding: 1.25rem 1.5rem; margin-bottom: 1rem;
    }
    .card h2 { font-size: 1rem; margin-bottom: 0.75rem; color: #79c0ff; display: flex; align-items: center; gap: 0.5rem; flex-wrap: wrap; }
    .card h2 code { background: #21262d; padding: 0.1rem 0.4rem; border-radius: 4px; font-size: 0.9rem; }
    .icon { font-size: 1rem; }
    .badge {
      font-size: 0.7rem; padding: 0.15rem 0.5rem; border-radius: 12px;
      font-weight: 600; text-transform: uppercase; letter-spacing: 0.05em;
    }
    .badge-added    { background: #1f4e2b; color: #56d364; }
    .badge-deleted  { background: #4e1f1f; color: #f85149; }
    .badge-modified { background: #1a2c4e; color: #58a6ff; }
    .badge-renamed  { background: #2d2000; color: #f0ad00; }
    .explanation { color: #c9d1d9; line-height: 1.6; margin-bottom: 0.75rem; }
    .risks { color: #d29922; line-height: 1.5; margin-bottom: 0.75rem; }
    .summary { color: #8b949e; line-height: 1.5; }
    .tag {
      display: inline-block; font-size: 0.7rem; padding: 0.1rem 0.45rem;
      border-radius: 4px; font-weight: 600; margin-right: 0.4rem; vertical-align: middle;
    }
    .risks-tag   { background: #2d1f00; color: #d29922; }
    .summary-tag { background: #1b2c1b; color: #56d364; }
    .global {
      background: #161b22; border: 1px solid #30363d; border-radius: 8px;
      padding: 1.25rem 1.5rem; margin-top: 1.5rem;
    }
    .global h2 { color: #56d364; margin-bottom: 0.75rem; }
    .global p { line-height: 1.6; }
    footer { text-align: center; color: #8b949e; font-size: 0.8rem; margin-top: 2rem; }
    footer a { color: #58a6ff; }
  </style>
</head>
<body>
  <h1>Why Changed</h1>
  <p class="meta">Generated by <a href="https://www.npmjs.com/package/why-changed">why-changed</a> on ${now}</p>
  ${fileCards}
  <div class="global">
    <h2>Overall Summary</h2>
    <p>${escape(globalSummary)}</p>
  </div>
  <footer>Made with ❤️ by <a href="https://github.com/Itaromi">Youn Sylvestre</a></footer>
</body>
</html>`;
}

// ─── File writers ─────────────────────────────────────────────────────────────

export function writeMarkdown(
  explanations: FileExplanation[],
  globalSummary: string,
  outputPath = 'CHANGES.md'
): string {
  const content = buildMarkdown(explanations, globalSummary);
  const resolved = path.resolve(outputPath);
  fs.writeFileSync(resolved, content, 'utf-8');
  return resolved;
}

export function writeHtml(
  explanations: FileExplanation[],
  globalSummary: string,
  outputPath = 'CHANGES.html'
): string {
  const content = buildHtml(explanations, globalSummary);
  const resolved = path.resolve(outputPath);
  fs.writeFileSync(resolved, content, 'utf-8');
  return resolved;
}
